services:
  vuln_dashboard.api:
    build:
      context: ./vendor/laravel/sail/runtimes/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.4/app
    ports:
      - '8000:8000'
    environment:
      WWWUSER: '${WWWUSER}'
      PORT: '8000'
      HOST: '0.0.0.0'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - pgsql
      - redis

  pgsql:
    image: postgres:15
    container_name: vuln-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: vuln_dashboard
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - sail

  redis:
    image: redis:7-alpine
    container_name: vuln-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  pgsql_data:
